[tool.poetry]
authors = [
  "Derek Ditch <dcode@elastic.co>",
  "Claire Burn <claire.burn@elastic.co>",
  "Sam Zeitlin <samantha.zeitlin@elastic.co>",
  "Jessica David <jessica.david@elastic.co>",
]
description = ""
name = "elastic.malware_config_extractor"
packages = [{include = "elastic"}]
readme = "README.md"
version = "8.1.0"

[tool.poetry.scripts]
extract-alerts = "elastic.malware_config_extractor.services.extract_alerts:main"
load-enriched-alerts = "elastic.malware_config_extractor.services.load_enriched_alerts:main"
malware-exquacker = "elastic.malware_config_extractor.console:main"
transform-alerts = "elastic.malware_config_extractor.services.transform_alerts:main"
transform-malduck = "elastic.malware_config_extractor.services.transform_malduck:main"

[tool.poetry.dependencies]
confluent-kafka = "1.6.0"
ecs-logging = "^1.1.0"
elasticsearch-dsl = "^7.4.0"
libcsce = "^0.1.0"
malduck = "^4.1.0"
marshmallow-dataclass = {extras = ["union"], version = "^8.5.3"}
pycrypto = "^2.6.1"
python = "^3.10"
requests = "^2.27.1"
"ruamel.yaml" = "^0.17.21"
scalpl = "^0.4.2"
setuptools = "^62.0.0"
typer = {extras = ["rich"], version = "^0.6.1"}

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
plyara = "^2.1.1"
pytest = "^7.1"
pytest-black = "^0.3.12"
pytest-datadir = "^1.3.1"
pytest-flake8 = "^1.0"
pytest-isort = "^3.0.0"
# yls = {git = "https://github.com/avast/yls.git"}
# yls-yara = "^1.1.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.pytest.ini_options]
minversion = "7.0"
# Disable pytest-black until they support pyproject.toml settings. See PR https://github.com/shopkeep/pytest-black/pull/64
#addopts                = "--black --isort --flake8"
addopts = "--isort --flake8"
flake8-ignore = "E203 E266 E501 W503"
flake8-max-line-length = 120
norecursedirs = "ecs"
testpaths = ["."]

[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.pylint.format]
max-line-length = 120

[tool.pyright]
exclude = ["**/__pycache__"]
include = ["elastic", "tests"]
