[tool.poetry]
name = "elastic.malware_config_extractor"
version = "8.1.0"
description = ""
authors = ["Derek Ditch <dcode@elastic.co>", "Claire Burn <claire.burn@elastic.co>", "Sam Zeitlin <samantha.zeitlin@elastic.co>"]
readme = "README.md"
packages = [{ include = "elastic" }]

[tool.poetry.scripts]
malware-config-extractor = 'elastic.malware_config_extractor.console:main'
# elastic-extractor = 'elastic.cobalt_strike_extractor.util.elastic_extractor:main'

[tool.poetry.dependencies]
python = "^3.9"
marshmallow-dataclass = { extras = ["union"], version = "^8.5.3" }
scalpl = "^0.4.2"
"ruamel.yaml" = "^0.17.21"
elasticsearch-dsl = "^7.4.0"
ecs-logging = "^1.1.0"
malduck = "^4.1.0"
setuptools = "^62.0.0"
libcsce = "^0.1.0"

[tool.poetry.group.dev.dependencies]


[tool.poetry.dev-dependencies]
pytest = "^6.0"
black = "^22.3.0"
flake8 = "^4.0.1"
pytest-black = "^0.3.12"
pytest-flake8 = "^1.0"
pytest-isort = "^3.0.0"
pytest-datadir = "^1.3.1"
requests = "^2.27.1"
pycrypto = "^2.6.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--black --isort --flake8"
testpaths = ["."]
norecursedirs = "ecs"
flake8-max-line-length = 88
flake8-ignore = "E203 E266 E501 W503"

[tool.isort]
profile = "black"

[tool.pyright]
include = ["elastic", "tests"]
exclude = ["**/__pycache__"]
