[tool.poetry]
name = "elastic.malware_config_extractor"
version = "0.1.0"
description = ""
authors = ["Derek Ditch <dcode@elastic.co>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
